### ISSUE TITLE
Won't compile on Python 3.8.5

### ISSUE THREAD

**Issue by abdulzakrt** [edomora97/beep-downloader#3]
The code wouldn't compile on python 3.8.5 

I get the following error:
  File "beep_downloader\__main__.py", line 53, in <module>
    main()
NameError: name 'main' is not defined

I solved it by moving 

"if __name__ == "__main__":
    main()
"

After the main function in __main__.py file

**Comment by edomora97** [comment]
Thanks!
This got unnoticed because I usually use the binary installed by setup.py. It should be ok now!
